name: CI Pipline for the platform

#event trigger on push and pull requests on the main branch
on:
  push:
      branches:
        - main
  pull_request:
     branches:
       - main

#Jobs

Jobs:

  # JOB1: build the system
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out the source code
        uses: actions/checkout@v7

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Compile application
        run: ./mvnw clean package -DskipTests

      - name: Save built artifact
        uses: actions/upload-artifact@v4
        with:
            name: app-jar
            path: target/*.jar

  # JOB2: test the system

  test:
    runs-on: ubuntu-latest

    steps:
      - name: test the system
        uses: actions/checkout@v7

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: run the test cases
        run: ./mvnw test
