spring.application.name=recommendations
debug=true

jwt.secret=64700240d89925c44bcad3e930a2ae6c15149bf4853cd2b377308f6d17436d71
jwt.expiration-time=54000000
#connect to the postgresql database with the host&username&password
spring.datasource.url=jdbc:postgresql://localhost:5432/Recommendations
spring.datasource.username=postgres
spring.datasource.password=postgres10
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

